server:
  port: 8080
spring:
  application:
    name: "ms-arithmetic-calculator"
  devtools:
    add-properties: false
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://rdmrosepmquohufhiams.supabase.co"
          client-id: "myclientid"
  r2dbc:
    url: r2dbc:postgresql://postgres.rdmrosepmquohufhiams:jdepaz2025@aws-0-us-east-2.pooler.supabase.com:6543/postgres
    username: postgres.rdmrosepmquohufhiams
    password: jdepaz2025
    host: aws-0-us-east-2.pooler.supabase.com
    port: 6543
    database: postgres
    pool:
      enabled: true
  # Flyway Configuration (para migraciones de base de datos)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
jwt:
  json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

