server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  devtools:
    add-properties: false
  profiles:
    include: ${SPRING_PROFILES_INCLUDE}
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET_KEY}
  r2dbc:
    url: "r2dbc:postgresql://${R2DBC_HOST}:${R2DBC_PORT}/${R2DBC_DATABASE}"
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
    host: ${R2DBC_HOST}
    port: ${R2DBC_PORT}
    database: ${R2DBC_DATABASE}
    pool:
      enabled: false
  flyway:
    enabled: true
    url: "jdbc:postgresql://${FLYWAY_HOST}:${FLYWAY_PORT}/${FLYWAY_DATABASE}"
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    driver: org.postgresql.Driver
jwt:
  json-exp-roles: ${JWT_JSON_EXP_ROLES:/roles}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}